### ISSUE TITLE
Finalize Name of App

### ISSUE THREAD

**Issue by CodeRISHI** [Preposterous-Platypus/Preposterous-Platypus#37]
After discussion with Zach on Friday, did we decide on just 'Platypus' as the name of our app or are we still sticking with Preposterous Platypus?

Update this Waffle with your votes (comment).

**Comment by ghost** [comment]
I'm thinking a name change is in order! But let's keep our logo :)

**Comment by cehsu** [comment]
How about "platter"? I'm fine with Platypus, although Zach made it clear that we would have to be able to link it with the concept. 
So for those who don't vote for Platypus, are there any proposals for a new name? So far two votes for sticking with Platypus...(assuming we can cleverly tie it in with the app concept)

**Comment by jreidgreer** [comment]
I vote 'Platypus'

**Comment by ghost** [comment]
Yeah, I agree with Claire. I think it's important that we have a name change so that it's clear with little explanation what our project is. Wasn't Zach saying that the other group who did the same project some time ago had a name like Snack Reactor? I like Platter, or even Hack Platter.

**Comment by jreidgreer** [comment]
Compromise? PlatyPlatter?

**Comment by kimcurran** [comment]
Hell no.

**Comment by jreidgreer** [comment]
Well then.

**Comment by jreidgreer** [comment]
I personally think it was Platytudes better than yours.

**Comment by ghost** [comment]
Can't roll my eyes enough.

**Comment by jreidgreer** [comment]
You're just mad that my Platypus game is on point.

**Comment by cehsu** [comment]
Platter it is! (unless it isn't, any other proposals?) how about Platy is the mascot....?

**Comment by jreidgreer** [comment]
Fineeee

**Comment by jreidgreer** [comment]
But we need to talk about these virtual work conditions Kim is subjecting me to.

**Comment by CodeRISHI** [comment]
Platter would make sense if it was jut about food I guess.. which it is for now. However, if we care about expanding the idea, that doesn't really work.

**Comment by jreidgreer** [comment]
Arun brings up a good point there. Back to Platypus I guess...

**Comment by ghost** [comment]
Haha. I think Platter works for what we have. When other groups expand it, that can be their issue :)

**Comment by CodeRISHI** [comment]
so the vote is between 1.) Platypus and 2.) Platter

cast your votes!!

**Comment by jreidgreer** [comment]
1 All the way

**Comment by ghost** [comment]
PLATTER

**Comment by jreidgreer** [comment]
WRITING IT IN ALL CAPS WON'T HELP YOU HERE

**Comment by CodeRISHI** [comment]
guys.. keep the comments professional - this is good practice for all of us. Plus, Zach can see them! :)

**Comment by jreidgreer** [comment]
@CodeRISHI You're not the boss of me. Last I checked, we're voting. #democracy #freedom #merica

**Comment by CodeRISHI** [comment]
I vote for #1 also (Platypus).

**Comment by cehsu** [comment]
I'm fine with Platypus as long as someone is willing to come up with some clever marketing language that ties in the animal to the app's concept (which I think Zach advised...? or am i misremembering), otherwise, I vote for Platter, so that no one has to come up with something clever to explain the name of the app.......? if I'm getting this mixed up and we don't need to justify our name, I'm fine with whatever the majority has deemed appropriate

**Comment by jreidgreer** [comment]
"Platypus: the iconic animal the represents the goofy but fun experience that is living in SF"

**Comment by ghost** [comment]
Yeah, I remember Zach's advice was that our name should be related to what our app is. I'm fine with Platypus as a name, but it just doesn't have anything to do with our project beyond being our team name.

**Comment by cehsu** [comment]
Would Reid have to revise any of the beautiful pages he has designed if we change the name?  If so, that might be more work that writing clever things, or coming up with cleverness that ties Platypi with social food finding

**Comment by jreidgreer** [comment]
So long as you don't go away from the color scheme and the like, changing the text isn't a big issue.

**Comment by cehsu** [comment]
I guess Platter wins by default...? unless someone would like to take the lead on writing up marketing cleverness, or feels that marketing cleverness that links Platypi and food finding is unnecessary?

**Comment by cehsu** [comment]
it's probably fine to keep all the mentions of platypus besides the text on the website design as they are, since it's our team name anyway?

**Comment by jreidgreer** [comment]
Umm... 2 votes against 2 votes doesn't mean one wins...

**Comment by cehsu** [comment]
I'd be willing to vote Platypus if anyone cares to make the case for using it besides the fact that it's our group's name? Platter is easy for people to understand, it's food related, i guess we could say something like, restaurant recommendations are served up on a platter to the user, as they're curated by their community...i dunno, anything clever either way works for me:) (I'm just thinking a name that doesn't have to be explained might make it easier on whoever wants to present, and in case someone asks after the presentation, we have an answer, especially potential employers :D )

**Comment by CodeRISHI** [comment]
Platterpus? XD

Platter works if it is just food-related; since that is not the case for the app as a whole, Platypus sounds just as incongruent as many of the startups out there.

So Platypus it is.
